#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
$:.unshift File.dirname(__FILE__)
require 'thrift'
require 'lucene_search_types'

module LuceneSearch
  class Client
    include ::Thrift::Client

    def search(query)
      send_search(query)
      return recv_search()
    end

    def send_search(query)
      send_message('search', Search_args, :query => query)
    end

    def recv_search()
      result = receive_message(Search_result)
      return result.success unless result.success.nil?
      raise result.error unless result.error.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'search failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_search(seqid, iprot, oprot)
      args = read_args(iprot, Search_args)
      result = Search_result.new()
      begin
        result.success = @handler.search(args.query)
      rescue LuceneSearchException => error
        result.error = error
      end
      write_result(result, oprot, 'search', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Search_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    QUERY = 1

    FIELDS = {
      QUERY => {:type => ::Thrift::Types::STRING, :name => 'query'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Search_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0
    ERROR = 1

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => Person}},
      ERROR => {:type => ::Thrift::Types::STRUCT, :name => 'error', :class => LuceneSearchException}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

